### ISSUE TITLE
爬虫规则

### ISSUE THREAD

**Issue by BolexLiu** [zoltsigg/itopdev#4]
如何做到抓取来自不同博客的内容，是单独去一个个做规则匹配，还是其它办法。期待你的回复。

**Comment by zoltsigg** [comment]
如果博客有RSS，就直接抓取RSS。 没有的话就需要寻找规则匹配了，但是大部分博客都是基于hexo的，写一个基于hexo的爬虫就能适应很多博客了，所以这部分的工作量也不是太大。

**Comment by BolexLiu** [comment]
谢谢你回复，明白了。我发现你对很多博主的资料都有做统计。包括这个人的介绍信息等。这个应该是手动的吧？

**Comment by zoltsigg** [comment]
对的，都是网上搜集的
